version: "3.9"

services:
  redis:
    image: redis:7.4-alpine
    expose:
      - "6379"
    volumes:
      - redis:/data
    networks:
      - net-ec
    container_name: redis-ec
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASS}"]
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASS}", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3

  nginx:
    depends_on:
      - api
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - api_data:/app/uploads:ro
    networks:
      - net-ec
    read_only: true
    image: nginx:1.27-alpine
    container_name: nginx-ec
    restart: unless-stopped
    tmpfs:
      - /var/cache/nginx
      - /var/run
  api:
    environment:
      APP_ENV: production
      DEBUG: "false"
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - redis
    read_only: true
    build:
      context: .
    container_name: api-ec
    restart: unless-stopped
    env_file:
      - .env
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    volumes:
      - api_data:/app/uploads
    networks:
      - net-ec
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://127.0.0.1:8000/api/v1/health"]
      interval: 30s
      timeout: 5s
      retries: 3



networks:
  net-ec:
    driver: bridge

volumes:
  redis:
  api_data: